apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-cluster-operator
  namespace: kafka
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-cluster-operator-global
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: [get, list, watch, create, update, patch]
  - apiGroups: [""]
    resources: [pods, services, configmaps, secrets, serviceaccounts, persistentvolumeclaims, events]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["apps"]
    resources: [deployments, statefulsets, replicasets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["policy"]
    resources: [poddisruptionbudgets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: [roles, rolebindings, clusterroles, clusterrolebindings]
    verbs: [get, create, delete, bind, update, patch, escalate]
  - apiGroups: ['routes.openshift.io']
    resources: ['routes']
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: ["monitoring.coreos.com"]
    resources: [servicemonitors, podmonitors, prometheuses]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: strimzi-cluster-operator
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: strimzi-cluster-operator-global
subjects:
    - kind: ServiceAccount
      name: strimzi-cluster-operator
      namespace: kafka

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: kafka
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strimzi-cluster-operator
  template:
    metadata:
      labels:
        app: strimzi-cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: strimzi/operator:0.43,0
          imagePullPolicy: IfNotPresent
          env:
            - name: STRIMZI_NAMESPACE
              value: "kafka"
            - name: STRIMZI_LOG_LEVEL
              value: "INFO"
            - name: STRIMZI_FEATURE_GATES
              value: +UseStrimziPodSets