apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.7.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9094
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "3.7"
      inter.broker.protocol.version: "3.7"
      default.replication.factor: 3
      min.insync.replicas: 2
      auto.create.topics.enable: true
      metric.reporters: io.strimzi.kafka.metrics.reporter.StrimziMetricsReporter
    storage:
      type: jbodd
      volumes:
        - id: 0
          type: persistent-claim
          size: 10Gi
          deleteClaim: true
      jmxOptions:
        enabled: true
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            name: kafka-metrics
            key: kafka-config.yaml
      template:
        pod:
          metadata:
            labels:
              monitoring: "true"
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: true
    jmxOptions:
      enabled: true
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-config.yaml
    entityOperator:
      topicOperator: {}
      userOperator: {}
    cruiseControl:
      config:
        cpu.capacity.threshold: 0.8
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            name: kafka-metrics
            key: cruisecontrol-config.yaml