apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus-deployment.yaml
  - prometheus-configmap.yaml
  - prometheus-operator-crds.yaml
  - grafana.yaml
  - alertmanager-deployment.yaml
  - alertmanager-service.yaml